# Sheelna kelmet 'version' 3ashan kanet bttl3lak warning asfar
services:
  worker-1:
    build: .
    command: uvicorn workers.gpu_worker:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    volumes:
      - hf_cache:/root/.cache/huggingface

  worker-2:
    build: .
    command: uvicorn workers.gpu_worker:app --host 0.0.0.0 --port 8002
    ports:
      - "8002:8002"
    volumes:
      - hf_cache:/root/.cache/huggingface

  worker-3:
    build: .
    command: uvicorn workers.gpu_worker:app --host 0.0.0.0 --port 8003
    ports:
      - "8003:8003"
    volumes:
      - hf_cache:/root/.cache/huggingface

  worker-4:
    build: .
    command: uvicorn workers.gpu_worker:app --host 0.0.0.0 --port 8004
    ports:
      - "8004:8004"
    volumes:
      - hf_cache:/root/.cache/huggingface

# Da el Shared Folder elly hy-sagel feeh el AI Model
volumes:
  hf_cache: {}